In [1]:
# 1.What is the difference between "static method" and "class method" in Python?

#...>A static method is a method bound to the class, not an instance of the class. It means it calls the class without creating an instance. 
# Static methods define utility functions that don't depend on the state of the example or the class.

#...>A class method is also bound to the class, but it takes a reference to the class itself as the first argument. 
# Defined methods operate on the class itself rather than on the instances of the class.
# Class methods are alternative constructors for the class, which can create class instances with different initial parameters.

In [3]:
# 2. How can you create a generator in Python?

#...>A generator is created using a function that contains the "yield" keyword.
# As the generator function is created, it returns a generator object to produce a sequence of values on-the-fly as the generator iterates.
# To create a generator function, define a function that contains one or more "yield" statements. 
# Each "yield" statement should produce a value for the generator to return.

In [5]:
# 3. What is the difference between "map" and "filter" functions in Python?

#...>"map" and "filter" are built-in functions operating on iterable objects. 
# The main difference between the two functions is that "map" applies a given function to each item in an iterable and returns an iterator with the results.
# In contrast, "filter" applies a given function to each item in an iterable and returns an iterator with only the things that meet the given condition.


In [7]:
# 4.How can you handle exceptions in Python?

#...>Exceptions are handled using a try-except block. The code that may raise an exception is put inside the "try" block, 
# and the exception handler is inside the "except" block. If the try block raises an exception, 
# the program flow is immediately transferred to the except block.

#...>The except block can be used to catch a specific or general exception and handle the exception by providing an appropriate message to the user or performing other actions.
# We can also use it to raise a new exception or re-raise the original exception. 

In [9]:
# 5.What is the difference between a "module" and a "package" in Python?

#...>A module is a single file containing Python code that can be imported and used in other Python codes.
# A module typically includes functions, classes, and variables used in other programs. Modules are a way to organize code and promote code reuse.

#...> a package is a collection of related modules organized into a directory structure.
# A package contains an init.py file executed while package importing.
# The init.py file can contain initialization code and define the package's interface by specifying which modules are part of the package. 

In [11]:
# 6. How to convert a list into a set?

#...> To convert a list into a set in Python, you can use the built-in set() function.
# This function takes an iterable object (such as a list) as input and returns a new set object that contains all the unique elements in the iterable.

my_list = [1, 2, 3, 3, 4, 4, 5]
my_set = set(my_list)
print(my_set)


{1, 2, 3, 4, 5}


In [13]:
# 7. How can you create Empty NumPy Array In Python?

#...>You can create an empty NumPy array in Python using the numpy.empty() function. 
# This function creates an array of a specified size and shape but with uninitialized entries. 

import numpy as np
# Create an empty array with shape (3, 4)
empty_arr = np.empty((3, 4))
print(empty_arr)

[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
 [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
 [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]


In [15]:
# 8.Write a code snippet to get an element, delete an element, and update an element in an array. 

import numpy as np
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Get an element
element = arr[2]
print("Element at index 2:", element)

# Delete an element
arr = np.delete(arr, 3) # Delete element at index 3
print("Array after deleting element at index 3:", arr)

# Update an element
arr[1] = 6 # Update element at index 1 to 6
print("Array after updating element at index 1:", arr)

Element at index 2: 3
Array after deleting element at index 3: [1 2 3 5]
Array after updating element at index 1: [1 6 3 5]


In [19]:
# 9. What is a lambda function? How are these written in Python?

#...>An anonymous function is also known as a lambda function. It can have any number of parameters but can have just one statement.
# Example...>

v = lambda p,q : p+q
print(v(7, 5))

12


In [21]:
# 10. How to reverse lists in Python using slicing?

import array as arr
a=arr.array('i',[1,2,3,4,5])
a[::-1]

array('i', [5, 4, 3, 2, 1])

In [25]:
# 11. What are the generators in Python?

#...>Functions that return an iterable set of items are called generators.
# Generators are functions that return iterable collection of items, one at a time, in a fixed manner. 
# Generators, generally, are used to create iterators with a different approach.


